[web]
13.60.61.104 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/min.pem
13.62.128.46 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/min.pem

[monitor]
51.20.40.34 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/min.pem

[mysql]
51.20.81.160 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/min.pem

[redis]
13.60.3.196 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/min.pem
